config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  devise_for :users
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to = user

  def self.search(search, word)
  return all if word.blank?

  if search == "perfect_match"
    where("nick_name = ?", "#{word}")
  elsif search == "forward_match"
    where("nick_name LIKE?", "#{word}%")
  elsif search == "backward_match"
    where("nick_name LIKE?", "%#{word}")
  elsif search == "partial_match"
    where("nick_name LIKE?", "%#{word}%")
  else
    all
  end
end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope->{order(created_at: :desc)}

    belongs_to :item, optional: true
    belongs_to :comment, optional: true
    belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
    belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true


end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :favorites, dependent: :destroy

         has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
         has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    puts "作成したキー #{ENV['SECRET_KEY']}"
  end

  def edit
    @book = Book.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  params.require(:comment).permit(:rate)

end

app/controllers/users.controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  private

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

  <h3>世界の天気</h3>
    <label>都市名：</label>
    <input id="cityname" type="text" size="14" maxlength="14" placeholder="Tokyo">
    <button id="btn">検索</button><br>
    <span>場所 :</span>
    <span id="place"></span><br>
    <span>最高気温 :</span>
    <span id="temp_max"></span>
    <span> ℃</span><br>
    <span>最低気温 :</span>
    <span id="temp_min"></span>
    <span> ℃</span><br>
    <span>湿度 :</span>
    <span id="humidity"></span>
    <span> %</span><br>
    <span>風速 :</span>
    <span id="speed"></span>
    <span> m/s</span><br>
    <span>天気 :</span>
    <span id="weather"></span>
    <div id="icon"><img id="img"></div>
    <script src="jquery.min.js"></script>
    <script src="script.js"></script>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/top.html.erb
<div class="row">
  <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>11章【タブメニューを作ってみよう】</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>
    <h1>11章【タブメニューを作ってみよう】</h1>

    <div class="wrap">
      <ul id="tab-menu">
        <li><a href="#tab1" class="active">TAB1</a></li>
        <li><a href="#tab2" class="">TAB2</a></li>
        <li><a href="#tab3" class="">TAB3</a></li>
        <li><a href="#tab4" class="">TAB4</a></li>
      </ul>

      <div id="tab-contents">
        <div id="tab1" class="tab">
          <p>TAB1のテキストが入ります。</p>
        </div>

        <div id="tab2" class="tab">
          <p>TAB2のテキストが入ります。TAB2のテキストが入ります。</p>
        </div>

        <div id="tab3" class="tab">
          <p>TAB3のテキストが入ります。TAB3のテキストが入ります。TAB3のテキストが入ります。</p>
        </div>

        <div id="tab4" class="tab">
          <p>TAB4のテキストが入ります。TAB4のテキストが入ります。TAB4のテキストが入ります。TAB4のテキストが入ります。</p>
        </div>
      </div>
      <div id="container">
      <div id="theTarget">
        <div class="image1"></div>
        <div class="image2"></div>
        <div class="image3"></div>
        <div class="image4"></div>
        <div class="image5"></div>
      </div>
    </div>
    </div>
    <script src="js/jquery.min.js"></script>
    <script src="js/script.js"></script>
  </body>
</html>

app/views/post_comments/show.html.erb
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
</div>

<div>
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% end %>
</div>
<div>
  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>


<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<%= form_with model: @comment, local: true , url: comments_path do |f| %>
    <%= f.text_area :content %><br>
    <%= f.hidden_field :post_id, value: @post.id %>
    <div class="field" id="star">
        <%= f.label :rate,  "星評価 (※必須)" ,id: "e"%>
        <%= f.hidden_field :rate, id: :review_star %>
    </div>
    <script>
        $('#star').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'comment[rate]',
        });
    </script>
    <%= f.submit %>
<% end %>

<% @comments.each do |comment| %>
    <p><%= comment.content %></p>
    <h4 class="mb-3">評価：<%= comment.rate %>点 </h4>
    <div id="star-rate-<%= comment.id %>"></div>
    <script>
          $('#star-rate-<%= comment.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            score: <%= comment.rate %>,
        });
    </script>
<% end %>